import { useNavigate } from 'react-router-dom'

export default function Landing() {
  const navigate = useNavigate()

  const features = [
    {
      title: 'Audience Segmentation',
      desc: 'Easily define custom audience segments based on customer behavior, such as total spending, visit frequency, and inactivity.',
      icon: '🎯'
    },
    {
      title: 'AI Campaign Creation',
      desc: 'Type your marketing goal in plain English and let AI build the perfect campaign — audience, channel, and message included.',
      icon: '🤖'
    },
    {
      title: 'Multi-Channel Delivery',
      desc: 'Reach your customers via WhatsApp, SMS, or Email with personalized messages generated by AI.',
      icon: '📡'
    },
    {
      title: 'Live Analytics',
      desc: 'Track delivery, open, click, and purchase rates in real time with AI-powered insights and retargeting advice.',
      icon: '📊'
    },
  ]

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">

      {/* Navbar */}
      <nav className="bg-white border-b border-gray-200 px-8 py-4 flex items-center justify-between">
        <span className="text-blue-600 font-bold text-xl">Xeno Mini CRM</span>
        <div className="flex gap-3">
          <button
            onClick={() => navigate('/home')}
            className="border border-gray-300 text-gray-700 px-5 py-2 rounded-lg text-sm font-medium hover:bg-gray-50"
          >
            Login
          </button>
          <button
            onClick={() => navigate('/home')}
            className="bg-blue-600 hover:bg-blue-700 text-white px-5 py-2 rounded-lg text-sm font-medium"
          >
            Signup
          </button>
        </div>
      </nav>

      {/* Hero */}
      <div className="flex-1 flex flex-col items-center justify-center text-center px-6 py-20">
        <h1 className="text-5xl font-bold text-gray-900 mb-4 max-w-3xl leading-tight">
          Build Campaigns & Manage Audiences Seamlessly
        </h1>
        <p className="text-gray-500 text-lg mb-10 max-w-xl">
          An AI-native CRM that turns your marketing goals into live campaigns in seconds.
        </p>
        <button
          onClick={() => navigate('/home')}
          className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-4 rounded-xl text-lg font-semibold shadow-md transition-colors"
        >
          Get Started →
        </button>

        {/* Feature Cards */}
        <div className="grid grid-cols-2 gap-6 mt-16 max-w-3xl w-full">
          {features.map((f) => (
            <div key={f.title} className="bg-white rounded-2xl border border-gray-200 p-6 text-left shadow-sm hover:shadow-md transition-shadow">
              <div className="text-3xl mb-3">{f.icon}</div>
              <h3 className="font-bold text-gray-900 text-lg mb-2">{f.title}</h3>
              <p className="text-gray-500 text-sm leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-400 text-center py-5 text-sm">
        © 2024 Xeno Mini CRM. All Rights Reserved.
      </footer>

    </div>
  )
}